version: '3.2'

name: quick-template

services:

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: 8.3
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
    command: [ "tail", "-f", "/dev/null" ]
    stop_signal: SIGQUIT
    restart: unless-stopped
    stop_grace_period: 60s
